import './globals.css'

import Footer from './sections/Footer'
import Header from './sections/Header'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Providers from './sections/Providers'

const inter = Montserrat({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800'] })

export const metadata: Metadata = {
  title: 'NextBasket - Bandage',
  description: 'Generated by create next app',
}

const links = [
  {
      title: 'Company Info',
      links: [
          {
              label: 'About Us',
              link: ''
          },
          {
              label: 'Carrier',
              link: ''
          },
          {
              label: 'We are hiring',
              link: ''
          },
          {
              label: 'Blog',
              link: ''
          }
      ]
  },
  {
      title: 'Legal',
      links: [
          {
              label: 'About Us',
              link: ''
          },
          {
              label: 'Carrier',
              link: ''
          },
          {
              label: 'We are hiring',
              link: ''
          },
          {
              label: 'Blog',
              link: ''
          }
      ]
  },
  {
      title: 'Features',
      links: [
          {
              label: 'Business Marketing',
              link: ''
          },
          {
              label: 'User Analytic',
              link: ''
          },
          {
              label: 'Live Chat',
              link: ''
          },
          {
              label: 'Unlimited Support',
              link: ''
          }
      ]
  },
  {
      title: 'Resources',
      links: [
          {
              label: 'IOS & Android',
              link: ''
          },
          {
              label: 'Watch a Demo',
              link: ''
          },
          {
              label: 'Customers',
              link: ''
          },
          {
              label: 'API',
              link: ''
          }
      ]
  }
]


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header/>
          {children}
          <Footer title='Bandage' links={links}/>
        </Providers>
      </body>
    </html>
  )
}

