import './globals.css'

import { Inter, Montserrat } from 'next/font/google'

import Footer from './components/Footer'
import Header from './components/Header'
import type { Metadata } from 'next'
import StoreProvider from './components/StoreProvider'

const inter = Montserrat({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800'] })

export const metadata: Metadata = {
  title: 'NextBasket - Bandage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header/>
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}

